# Crecimiento poblacional

Consideremos que la edad máxima de un miembro de la población es $L$ años, entonces los siguientes $n$ intervalos representan los grupos de edad.

$\left[ 0, \frac{L}{n} \right)$

$\left[ \frac{L}{n}, \frac{2L}{n} \right)$ ...

...  así sucesivamente hasta
 
$\left[ \frac{(n-1)L}{n}, L \right]$

El vector de la distribución de edades $\vec{x}$ representa el número de miembros que componen cada grupo de edad

$\vec{x} =\left[ \begin{array}{cccc}
x_{1} \\
x_{2} \\
x_{3} \\
...\\
x_{n}\end{array} \right]$

Durante un periodo de $L/n$ años, la probabilidad de que un miembro del i-ésimo grupo de edad sobreviva para ingresar al grupo de edad (i+1) esta dada por $p_i$, donde

$0\leq p_i \leq 1, i = 1,2,3, ..., n-1$

El número promedio de descendientes por miembro del i-ésimo grupo de edad esta dado pro $b_i$

Estas cantidades pueden representarse en forma matricial de la siguiente manera

$A = \left[ \begin{array}{cccccc}
b_{1} & b_{2} & \ldots & b_{n-1} & b_{n} \\
p_{1} & 0     & \ldots & 0       & 0     \\
0     & p_2   & \ldots & 0       & 0     \\ 
.     & . & \ldots & .       & .     \\
.     & . & \ldots & .       & .     \\ 
.     & . & \ldots & .       & .     \\ 
0     & 0 & \ldots & p_{n-1}       & 0     \\ 
0     & 0 &\ldots & 0      & p_{n}    
\end{array} \right]$

donde $A$ se conoce como la matriz de **transición de edades**, entonces multiplicando $A$ por el vector de distribución de edades $\vec{x}$ de un periodo específico produce el vector de distribuciones de edades del siguiente periodo, es decir:

$A\vec{x_i} = \vec{x}_{i+1} $



# Ejemplo:

Consideremos que una población de conejos tiene las siguientes características:

1. La mitad de la población de conejos sobrevive el primer año. De los cuales la mitad sobrevive el segundo año y la edad maxima de vida es de 3 años
2.  Durante el primer año, los conejos no producen descendencia. El número promedio de descendientes durante el segundo año es 6 y 8 durante el tercero.

La población ahora consiste de 24 conejos en el primer grupo de edades, 24 en el segundo y 20 en el tercero. ¿Cuántos conejos habrá en cada grupo de edad dentro de un año?


Resolver en clase con participación de estudiantes ...

In [1]:
import numpy as np

In [2]:
L = 3
n = 3
p1 = 0.5
p2 = 0.5
p3 = 0
b1 = 0 
b2 = 6
b3 = 8

A = np.array([[b1,b2,b3],[p1,0,0],[0,p2,0]])
A

x1 =24
x2 =24
x3 =20
x_1 = np.array([x1,x2,x3])
A,x_1

(array([[0. , 6. , 8. ],
        [0.5, 0. , 0. ],
        [0. , 0.5, 0. ]]),
 array([24, 24, 20]))

Para determinar la distribución de edades en el momento $i+1$ tenemos que realizar la siguiente operación $A\vec{x_i} = \vec{x}_{i+1} $

In [3]:
x_2 = A.dot(x_1)
x_2

array([304.,  12.,  12.])

In [4]:
x_3 = A.dot(x_2)
x_3

array([168., 152.,   6.])